
export const LOCATION_NAME_PREFIX: string[] = [
  'New',
  'South',
  'The merchant district of',
  'The healer\'s quarter in',
  'The fisherman\'s quarter in',
  'A tavern in',
  'The lower district of',
  'The high district of',
  'Olde',
  'The outskirts of',
  'The village of',
  '',
  '',
  'A camp near',
  'North',
];
export const LOCATION_NAMES: string[] = [
  'Charlesberg',
  'Tomberg',
  'Hampsville',
  'Westville',
  'Fankton',
  'Steville',
  'Swindon',
  'Icemeet',
  'Wingston',
  'Westray',
  'Walden',
  'Pirn',
  'Lullin',
  'Berkshire',
  'Queenstown',
  'Breckenridge',
  'Amour',
];
